interface RawUser {
  about: string | unknown;
  active: boolean;
  avatar_url: string;
  banner_url: string;
  id: string;
  is_following: boolean;
  likes_count: number;
  name: string;
  username: string;
  is_official_creator: boolean;
  is_official: boolean;
  label: string | unknown;
  appeal_image_urls: string[];
  back_number_post_images_count: number;
  back_number_post_videos_count: number;
  cant_receive_message: boolean;
  current_back_number_plan: string | unknown;
  followers_count: number;
  following_count: number;
  has_approved_user_identification: boolean;
  is_bought_back_number: boolean;
  is_followed: boolean;
  is_subscribed: boolean;
  limited_posts_count: number;
  link_instagram_id: string | unknown;
  link_instagram_url: string | unknown;
  link_tiktok_id: string | unknown;
  link_tiktok_url: string | unknown;
  link_twitter_id: string | unknown;
  link_twitter_url: string | unknown;
  link_youtube_url: string | unknown;
  post_images_count: number;
  post_videos_count: number;
  posts_count: number;
  sns_link1: string | unknown;
  sns_link2: string | unknown;
  birthday: string | unknown;
  comment_permission: string;
  disallow_receive_message: boolean;
  email: string;
  is_confirmed: boolean;
  is_creater: boolean;
  unread_notifications_count: number;
}
